# Generated by Django 5.1.6 on 2025-02-27 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
