# Generated by Django 5.1.6 on 2025-02-28 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_views'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
