# Generated by Django 5.1.6 on 2025-03-03 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_cart_total_price_alter_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='total_price',
            new_name='price',
        ),
    ]
